### ISSUE TITLE
Installation via environment

### ISSUE THREAD

**Issue by LorenzoScipioni** [juglab/PPN2V#10]
I tried installing via .yml but got a "ResolvePackageNotFound" error on a bunch of libraries (file attached). Here's what I did:

on the .yml link -> open this file in GitHub Desktop (the folder is cloned in my system)
Anaconda prompt -> cd "....\PPN2V"
conda env create -f ppn2vEnvironment.yml
Collecting package metadata (repodata.json): done -> Solving environment: failed
Below the packages returned as not found

ResolvePackageNotFound:
  - pyqt==5.9.2=py37h05f1152_2
  - pytorch==1.1.0=py3.7_cuda9.0.176_cudnn7.5.1_0
  - intel-openmp==2019.4=243
  - fontconfig==2.13.0=h9420a91_0
  - python==3.7.4=h265db76_1
  - qt==5.9.7=h5867ecd_1
  - tk==8.6.8=hbc83047_0
  - numpy==1.17.2=py37haad9e8e_0
  - xz==5.2.4=h14c3975_4
  - mkl_random==1.1.0=py37hd6b4f25_0
  - icu==58.2=h9c2bf20_1
  - ninja==1.9.0=py37hfd86e86_0
  - nodejs==12.4.0=he1b5a44_0
  - libxml2==2.9.9=hea5a465_1
  - libxcb==1.13=h1bed415_1
  - freetype==2.9.1=h8a8886c_1
  - openssl==1.1.1d=h516909a_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - libedit==3.1.20181209=hc058e9b_0
  - numpy-base==1.17.2=py37hde5b4d6_0
  - tifffile==0.15.1=py37h3010b51_1001
  - pcre==8.43=he6710b0_0
  - pyzmq==18.1.0=py37he6710b0_0
  - kiwisolver==1.1.0=py37he6710b0_0
  - gstreamer==1.14.0=hb453b48_1
  - zstd==1.3.7=h0b5b093_0
  - torchvision==0.3.0=py37_cu9.0.176_1
  - mistune==0.8.4=py37h516909a_1000
  - cffi==1.13.0=py37h2e261b9_0
  - jpeg==9b=h024ee3a_2
  - mkl-service==2.3.0=py37he904b0f_0
  - cytoolz==0.10.1=py37h516909a_0
  - zeromq==4.3.1=he6710b0_3
  - sqlite==3.30.1=h7b6447c_0
  - zlib==1.2.11=h7b6447c_3
  - pillow==6.2.0=py37h34e0f95_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - tornado==6.0.3=py37h7b6447c_0
  - matplotlib==3.1.1=py37h5429711_0
  - readline==7.0=h7b6447c_5
  - libsodium==1.0.16=h1bed415_0
  - sip==4.19.8=py37hf484d3e_0
  - expat==2.2.6=he6710b0_0
  - mkl_fft==1.0.14=py37ha843d7b_0
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - libgcc-ng==9.1.0=hdf63c60_0
  - cudatoolkit==9.0=h13b8566_0
  - ncurses==6.1=he6710b0_1
  - scipy==1.3.1=py37h7c811a0_0
  - pywavelets==1.1.1=py37hc1659b7_0
  - pyrsistent==0.15.6=py37h516909a_0
  - scikit-image==0.15.0=py37he6710b0_0
  - dbus==1.13.12=h746ee38_0
  - libffi==3.2.1=hd88cf55_4
  - libpng==1.6.37=hbc83047_0
  - libuuid==1.0.3=h1bed415_2
  - libtiff==4.0.10=h2733197_2
  - glib==2.56.2=hd408876_0
  - markupsafe==1.1.1=py37h516909a_0
  - ptyprocess==0.6.0=py37_0
  - mkl==2019.4=243

**Comment by CatEek** [comment]
What OS and conda version are you using ?

**Comment by LorenzoScipioni** [comment]
Sorry for the super late reply :O 
OS is windows 11 and conda 22.9.0

**Comment by jdeschamps** [comment]
We should add an "how to install" section in the readme as installing from the .yml often leads to complications.

**Comment by jdeschamps** [comment]
solved with this https://github.com/juglab/PPN2V/pull/4 actually
